In [2]:
import numpy as np
import pandas as pd

# import like this
items_path = "items.csv"
q1_path = "quarter-1.csv"
q2_path = "quarter-2.csv"
q3_path = "quarter-3.csv"


q1= pd.read_csv(q1_path)
q2 = pd.read_csv(q2_path)
q3 = pd.read_csv(q3_path)

items = pd.read_csv(items_path)

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
df = pd.concat((q1,q2,q3),keys=['Q1','Q2','Q3'])

In [6]:
df

        order_id quantity item_id choice_description_id item_price
Q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
Q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [11]:
df = df.reset_index()

In [12]:
df

,level_0,level_1,order_id,quantity,item_id,choice_description_id,item_price
0,Q1,0,1,1,1,1,$3.39
1,Q1,1,1,1,2,2,$3.39
2,Q1,2,2,2,4,3,$16.98
3,Q1,3,4,1,7,6,$9.25
4,Q1,4,6,1,9,8,$8.75
...,...,...,...,...,...,...,...
4617,Q2,2342,1829,1,23,92,$11.25
4618,Q2,2343,1830,1,23,1043,$11.25
4619,Q2,2344,1832,1,10,116,$8.75
4620,Q2,2345,1832,1,8,0,$4.45
4621,Q2,2346,1834,1,20,515,$11.25

In [13]:
items

    item_id                              item_name
0         0           Chips and Fresh Tomato Salsa
1         1                                   Izze
2         2                       Nantucket Nectar
3         3  Chips and Tomatillo-Green Chili Salsa
4         4                           Chicken Bowl
5         5                          Side of Chips
6         6                          Steak Burrito
7         7                       Steak Soft Tacos
8         8                    Chips and Guacamole
9         9                   Chicken Crispy Tacos
10       10                     Chicken Soft Tacos
11       11                        Chicken Burrito
12       12                            Canned Soda
13       13                       Barbacoa Burrito
14       14                       Carnitas Burrito
15       15                          Carnitas Bowl
16       16                          Bottled Water
17       17  Chips and Tomatillo Green Chili Salsa
18       18                          Barbacoa Bowl
19       19                                  Chips
20       20                     Chicken Salad Bowl
21       21                             Steak Bowl
22       22                    Barbacoa Soft Tacos
23       23                         Veggie Burrito
24       24                            Veggie Bowl
25       25                     Steak Crispy Tacos
26       26    Chips and Tomatillo Red Chili Salsa
27       27                  Barbacoa Crispy Tacos
28       28                      Veggie Salad Bowl
29       29     Chips and Roasted Chili-Corn Salsa
30       30     Chips and Roasted Chili Corn Salsa
31       31                    Carnitas Soft Tacos
32       32                          Chicken Salad
33       33                      Canned Soft Drink
34       34                       Steak Salad Bowl
35       35                      6 Pack Soft Drink
36       36    Chips and Tomatillo-Red Chili Salsa
37       37                                   Bowl
38       38                                Burrito
39       39                           Crispy Tacos
40       40                  Carnitas Crispy Tacos
41       41                            Steak Salad
42       42      Chips and Mild Fresh Tomato Salsa
43       43                      Veggie Soft Tacos
44       44                    Carnitas Salad Bowl
45       45                    Barbacoa Salad Bowl
46       46                                  Salad
47       47                    Veggie Crispy Tacos
48       48                           Veggie Salad
49       49                         Carnitas Salad

In [15]:
df = df.merge(items, on='item_id')

In [16]:
df

,level_0,level_1,order_id,quantity,item_id,choice_description_id,item_price,item_name
0,Q1,0,1,1,1,1,$3.39,Izze
1,Q1,10,12,1,1,18,$3.39,Izze
2,Q1,25,21,1,1,33,$3.39,Izze
3,Q1,34,30,1,1,33,$3.39,Izze
4,Q1,179,155,1,1,33,$3.39,Izze
...,...,...,...,...,...,...,...,...
4617,Q2,1411,1094,1,48,755,$8.49,Veggie Salad
4618,Q2,1528,1192,1,48,149,$8.49,Veggie Salad
4619,Q2,1605,1263,1,48,306,$8.49,Veggie Salad
4620,Q2,1745,1395,1,48,755,$8.49,Veggie Salad
4621,Q2,826,668,1,47,217,$8.49,Veggie Crispy Tacos

In [22]:
df.groupby(['level_0','item_name'],as_index=False)['quantity'].sum().sort_values('quantity',ascending=False).drop_duplicates(subset=['level_0'])

   level_0     item_name quantity
65      Q2  Chicken Bowl      394
17      Q1  Chicken Bowl      367

In [26]:
df["price"]= df['item_price'].apply(lambda x: float(x[1:]))

In [28]:
df['total_price'] = df['price']*df['quantity']

In [35]:
df.groupby(['level_0','item_name'],as_index=False)['total_price'].sum().sort_values('total_price',ascending=False).drop_duplicates(subset=['level_0'])

   level_0     item_name total_price
65      Q2  Chicken Bowl     4192.25
17      Q1  Chicken Bowl     3852.38